# Generated by Django 6.0.2 on 2026-02-15 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingzone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingzone',
            name='parking_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_zones', to='parking.parkingfacility'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='parking.parkingzone')),
            ],
        ),
    ]
