# Generated by Django 6.0.2 on 2026-02-15 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_telemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_logs', to='parking.device')),
            ],
            options={
                'unique_together': {('device', 'timestamp')},
            },
        ),
    ]
