# Generated by Django 6.0.2 on 2026-02-15 18:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkinglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('DEVICE_OFFLINE', 'Device Offline'), ('HIGH_POWER', 'High Power Usage'), ('INVALID_DATA', 'Invalid Data')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=20)),
                ('message', models.TextField()),
                ('first_triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='parking.device')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('target_parking_events', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parking_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='parking.parkingzone')),
            ],
            options={
                'unique_together': {('parking_zone', 'date')},
            },
        ),
    ]
